site_name: piqtree
site_url: "https://github.com/iqtree/piqtree"
site_author: "Gavin Huttley"
repo_url: "https://github.com/iqtree/piqtree"
repo_name: 'GitHub'
theme:
    name: material
    features:
      - navigation.indexes
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - text
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            docstring_style: numpy
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - mkdocs-jupyter:
      include_requirejs: true
      execute: true
      remove_tag_config:
          remove_input_tags:
              - hide_code

nav:
  - Introduction: index.md
  - Quickstart:
    - quickstart/index.md
    - quickstart/construct_ml_tree.md
    - quickstart/fit_tree_topology.md
    - quickstart/using_substitution_models.md
    - quickstart/using_model_finder.md
    - quickstart/calculate_jc_distances.md
    - quickstart/construct_nj_tree.md
    - quickstart/make_random_trees.md
    - quickstart/calculate_rf_distances.md
  - API reference:
    - api/index.md
    - Trees:
      - api/tree/build_tree.md
      - api/tree/fit_tree.md
      - api/tree/nj_tree.md
      - api/tree/random_trees.md
    - Substitution Models:
      - api/model/model_finder.md
      - api/model/Model.md
      - api/model/SubstitutionModel.md
      - api/model/FreqType.md
      - api/model/RateModel.md
    - Genetic Distances:
      - api/genetic_distance/jc_distances.md
    - Tree Distances:
      - api/tree_distance/robinson_foulds.md
  - Apps:
    - Available Apps: apps/available_help.py
    - Selecting models for phylogenetic analysis: apps/model_finder.py
    - Estimate a phylogenetic tree: apps/phylo.py
    - Fit a model to one tree: apps/fit_tree.py
    - Phylogenetic model options: apps/options.py
    - Pairwise JC distances: apps/pairwise_dist.py
    - NJ tree: apps/nj.py
    - Parallel processing across alignments: apps/app_pipeline.py
  - Citation: citation.md
